name = "mymail-mcp"
main = "src/index.ts"
compatibility_date = "2026-06-14"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyMCP"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"

[[routes]]
pattern = "mcp.casperovid.no/*"
zone_name = "casperovid.no"

[[kv_namespaces]]
binding = "EMAIL_KV"
id = "ef2884498da64a66a91ae34f8517d09a"

[vars]
GITHUB_CLIENT_ID = "Ov23liUlzwBp2iwoXO4A"
ALLOWED_GITHUB_LOGIN = "casperovid"
TEAM_DOMAIN = "https://placeholder.cloudflareaccess.com"
POLICY_AUD = "placeholder"
OUTLOOK_TENANT = "consumers"
OUTLOOK_CLIENT_ID = ""

[observability]
enabled = true
